function fig2_like(Y1, Y2)
%CREATEFIGURE(Y1, Y2)
%  Y1:  vector of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 08-May-2020 23:32:22

% Create figure
figure('OuterPosition',[395 344 576 395]);

% Create axes
axes1 = axes;
hold(axes1,'on');

% Activate the left side of the axes
yyaxis(axes1,'left');
% Create plot
plot(Y1,'DisplayName','Acc','Color',[0 0 0]);

% Set the remaining axes properties
set(axes1,'YColor',[0 0 0],'YMinorTick','off','YScale','linear');
% Activate the right side of the axes
yyaxis(axes1,'right');
% Create plot
plot(Y2,'DisplayName','Loss',...
    'Color',[0.588235294117647 0.250980392156863 0.105882352941176]);

% Set the remaining axes properties
set(axes1,'YColor',[0 0 0],'YMinorTick','off','YScale','linear');
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 622]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'LineStyleOrderIndex',2,'YGrid','on','YMinorGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.767559525326245 0.60209713340069 0.137499998616321 0.120860923994456]);

